#!/usr/bin/env bash

# set -e: exit asap if a command exits with a non-zero status
# set -x: print each command right before it is executed
set -xe

# sudo apt-get install -qyy tree

docker --version || echo "INFO: No docker installed yet"

sudo ./CI/before_install_docker

docker --version || (echo "FATAL: No docker installed" && exit 1)
