#!/usr/bin/env bash
# Runs one of the tests scenarios

# set -e: exit asap if a command exits with a non-zero status
# set -x: print each command right before it is executed
set -xe

# echo fn that outputs to stderr http://stackoverflow.com/a/2990533/511069
echoerr() {
  cat <<< "$@" 1>&2;
}

# print error and exit
die () {
  echoerr "ERROR: $1"
  # if $2 is defined AND NOT EMPTY, use $2; otherwise, set to "3"
  errnum=${2-3}
  exit $errnum
}

# Required params
[ -z "${1}" ] && die "Need first argument to be the test name, i.e. scenario directory"
test_name=${1}
[ -z "${2}" ] && die "Need second argument to be the test type (basic/advan)"
test_type=${2}
[ -z "${3}" ] && die "Need third argument test language (java/js)"
test_lang=${3}

echo "#================================"
echo "# Scenario ${test_name}"
echo "#================================"

echo "Starting ${test_lang} tests..."
cd ${test_name}

if [ "${test_lang}" = "java" ]; then
  java -version
  mvn --version
  cd java-*

  if [ "${test_type}" = "basic" ]; then
    mvn test
  elif [ "${test_type}" = "advan" ]; then
    echo "#========================="
    echo "# ${test_name} - Initial"
    echo "#========================="
    cd initial
    mvn test

    echo "#========================="
    echo "# ${test_name} - Complete"
    echo "#========================="
    cd ../complete/
    mvn test
    # back to java-testng dir
    cd ..
  else
    die "Fatal, test_type is not either 'basic' nor 'advan'"
  fi
elif [ "${test_lang}" = "js" ]; then
  node --version
  cd js-*

  if [ "${test_type}" = "basic" ]; then
    npm install
    npm test
  elif [ "${test_type}" = "advan" ]; then
    cd initial
    npm install
    npm test
    cd ../complete/
    npm install
    npm test
    # back to js-mocha-chai dir
    cd ..
  else
    die "Fatal, test_type is not either 'basic' nor 'advan'"
  fi
fi

